### ISSUE TITLE
Quiver timeline - add GT filters

### ISSUE THREAD

**Issue by MareenGeestmann** [OCR-D/quiver-frontend#68]
Add filters

- GT metadata: 
- publication year
- place of printing
- (text type)

- GT labels

**Comment by jfrer** [comment]
Is the date range (notBefore, notAfter) meant by publication year? 
What does the text type mean? Is it "language" or "script"? 
Also I can't find the place of printing in the gt metadata.

**Comment by jfrer** [comment]
Another question: should these filters only be added to the timeline view like the filters in #45?

**Comment by MareenGeestmann** [comment]
Yes, use the date range for filtering.

Text type refers to "script". (See https://ocr-d.de/gt-metadata/document-your-gt.html under "Document Type".)

Regarding the "place of printing": There is no information on this in the API so far. It may be possible to obtain the place of publication from the METS, but there has been no request for this so far.

Yes, only for timeline view.

**Comment by jfrer** [comment]
Ok, thanks. 
The date range filter is already implemented as it was part of #45.

Should I just implement the script-type filter and the label filter then and skip the "place of printing" for now?
Also, just as a notice: The script-type filter won't filter anything at the moment since all the gts have the same script-type "print".

**Comment by MareenGeestmann** [comment]
Yes, skip the "place of printing" for now.
