### ISSUE TITLE
quiver frontend - display more GT metadata

### ISSUE THREAD

**Issue by MareenGeestmann** [OCR-D/quiver-frontend#69]
display more ground truth metadata

where: under short title, nice and clear

following metadata for one document:
- "url"
- "language"
- "script"
- "script-type"
- "license"
- "volume"
- "labelling"

in addition, display metadata of corresponding corpus:
(this can be displayed in an expandable way so that it does not become too expansive)
- metadata as for document
- summary
- additional labels
- link to corpus in GitHub

**Comment by jfrer** [comment]
One of the GT data entrys has a data structure under "volume" that differs from all the others:
The 5th item [here](https://quiver-dev.sub.uni-goettingen.de/api/gt) with the id `reichsanzeiger_random` has the following structure (metric and count for each entry as as seperate object in a list):
`"volume": [
  {
   "metric": "lines",
   "count": 119435
  },
 {
  "metric": "pages",
  "count": 197
 }
]`
...while the other entries have this structure ("metric": "count" as an attribute for each entry): 
`"volume": {
  "TxtRegion": "21",
  "GraphRegion": "1",
  "SepRegion": "2",
  "TextLine": "87",
  "Page": "3"
}`
Should I deal with the outlier or is this a bug that will get fixed in the backend?

**Comment by MareenGeestmann** [comment]
> Should I deal with the outlier or is this a bug that will get fixed in the backend?

@mweidling Could you please have a look at it?

**Comment by jfrer** [comment]
> in addition, display metadata of corresponding corpus:
(this can be displayed in an expandable way so that it does not become too expansive)

I can't find this data. Is there an API for this, that I haven't found yet?

**Comment by mweidling** [comment]
> > Should I deal with the outlier or is this a bug that will get fixed in the backend?
> 
> @mweidling Could you please have a look at it?

Yes. The structure as presented in `reichsanzeiger` (the one with the array) is the correct one.

**Comment by jfrer** [comment]
> > in addition, display metadata of corresponding corpus:
> > (this can be displayed in an expandable way so that it does not become too expansive)
> 
> I can't find this data. Is there an API for this, that I haven't found yet?

Because there currently is no API for this, this can't be implemented yet. If this needs to be implemented later on, please create a new ticket.
